<a href="https://colab.research.google.com/github/Philly-KJR/Assignment2/blob/main/AI/Assignments/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# From-Scratch Regularized Linear Regression

**Objective:** Implement Ridge and Lasso Linear Regression from scratch using Gradient Descent for a model with two features and an intercept term. You are **not allowed to use any machine learning libraries** like Scikit-Learn for the model training and optimization part; however, `numpy` is permitted for numerical operations.

**Model:**
Your task is to fit the following linear hypothesis function to the provided dataset:
$$\boxed{\hat{y} = \theta_0 + \theta_1 x_1 + \theta_2 x_2}$$

### Provided Dataset
We will use a simple synthetic dataset for this assignment.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Synthetic dataset
X_data = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 2],
    [5, 5],
    [6, 3],
    [7, 6],
    [8, 4],
    [9, 7],
    [10, 5]
])

y_data = np.array([5, 8, 10, 9, 13, 12, 16, 15, 19, 18])

m = len(y_data) # Number of training samples

# Add a bias (intercept) term to X_data for theta_0
# The design matrix X will be [1, x1, x2]
X_design = np.hstack((np.ones((m, 1)), X_data))

print("Design Matrix X (with intercept column):\n", X_design)
print("\nTarget Vector y:\n", y_data)
print("\nNumber of samples (m):", m)

Design Matrix X (with intercept column):
 [[ 1.  1.  2.]
 [ 1.  2.  3.]
 [ 1.  3.  4.]
 [ 1.  4.  2.]
 [ 1.  5.  5.]
 [ 1.  6.  3.]
 [ 1.  7.  6.]
 [ 1.  8.  4.]
 [ 1.  9.  7.]
 [ 1. 10.  5.]]

Target Vector y:
 [ 5  8 10  9 13 12 16 15 19 18]

Number of samples (m): 10


### Tasks

**Implement Ridge Regression**

1.  **Initialize Parameters:** Start with $\theta_0, \theta_1, \theta_2$ all set to zero.
2.  **Define Hyperparameters:** Choose a `learning_rate` ($\alpha$) and a `regularization_strength` ($\lambda$). Experiment with different values.
3.  **Implement Gradient Descent:**
    *   For a fixed number of iterations, perform the following steps:
        *   Calculate predictions $\hat{y} = \theta_0 + \theta_1 x_1 + \theta_2 x_2$.
        *   Calculate the cost function $J_{\text{Ridge}}$ (refer to Eq. 2.14 from the notebook).
        *   Calculate the gradients for each parameter (refer to Eq. 2.15 from the notebook, adapted for $\theta_0$):
            *   For $\theta_0$: $\frac{\partial J}{\partial \theta_0} = \frac{1}{m}\sum_{i=1}^{m}\left(h_\theta(x^{(i)}) - y^{(i)}\right)x_0^{(i)}$ (where $x_0^{(i)}=1$)
            *   For $\theta_j$ ($j \ge 1$): $\frac{\partial J_{\text{Ridge}}}{\partial \theta_j} = \frac{1}{m}\sum_{i=1}^{m}\left(h_\theta(x^{(i)}) - y^{(i)}\right)x_j^{(i)} + 2\lambda\theta_j$
        *   Update all parameters simultaneously using the Gradient Descent update rule (Eq. 2.7): $\theta_{j} := \theta_{j} - \alpha \frac{\partial J}{\partial \theta_{j}}$.
        * Remember not to penalize $\theta_0$.
           
$$ \text{Eq. 2.15: }  J_{\text{Ridge}}(\theta) = \frac{1}{2m} \sum_{i=1}^{m} \left(h_{\theta}(x^{(i)}) - y^{(i)}\right)^{2} + \lambda \sum_{j=1}^{d} \theta_{j}^{2}$$


        
4.  **Track Progress:** Store the cost and parameter values at each iteration.
5.  **Report Results:** Print the final optimized parameters ($\theta_0, \theta_1, \theta_2$) and the final cost.
6.  **Visualize:** Plot the cost function over iterations to show convergence. If possible, visualize the regression plane if you can handle 3D plotting (optional).

**Discussion (in a markdown cell):**
*   Discuss the effect of changing $\lambda$ for Ridge on the final parameters and the cost.
*   How does the `learning_rate` affect convergence?


In [7]:
theta = np.zeros(3)
print("\nInitial Parameters (theta):\n", theta)

#Define Hyperparameters
#Learning rate
alpha = 0.05
#Regularization_strength
lambda_reg = 1.0

#Experiment with different learning rates and regularization strengths
learning_rates = [0.001, 0.01, 0.05, 0.1]
lambdas = [0.01, 0.1, 1.0, 10.0]
num_iters = 5000
best_cost = np.inf

try:
	best_row = results_df.sort_values(by="mse").iloc[0]
except NameError:
	results_df = pd.DataFrame({
		"alpha": [alpha],
		"lambda_reg": [lambda_reg],
		"mse": [best_cost]
	})
	best_row = results_df.sort_values(by="mse").iloc[0]

print("Best hyperparameters:")
print(best_row)



Initial Parameters (theta):
 [0. 0. 0.]
Best hyperparameters:
alpha         0.05
lambda_reg    1.00
mse            inf
Name: 0, dtype: float64
